### ISSUE TITLE
How to send SMS instead of email 

### ISSUE THREAD

**Issue by kirti301290** [hunk/get-UDID#1]
this sample code it working fine
but our requirement  is send sms instead of email so how we can do customize  it 
also can you provide step to produce .mobileconfige file so  we can host to our server

**Comment by hunk** [comment]
Hello, you can change/add a [little HTML for this](https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/SMSLinks/SMSLinks.html#//apple_ref/doc/uid/TP40007899-CH7-SW1)

about the mobileconfig check this links

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/iPhoneOTAConfiguration/profile-service/profile-service.html

https://ryanbritton.com/2016/07/creating-a-mobileconfig-file-to-capture-ios-udid-information/

http://www.joshwright.com/tips/getting-an-iphone-udid-from-mobile-safari

**Comment by kirti301290** [comment]
Thanks you for reply tried to create .mobileconfig file  but it guve me
error 'invalid profile' is there any way  to change your existing
mobileconfi file
Thanks

On May 22, 2017 12:47 AM, "Edgar G @hunk" <notifications@github.com> wrote:

Hello, you can change/add a little HTML for this
<https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/SMSLinks/SMSLinks.html#//apple_ref/doc/uid/TP40007899-CH7-SW1>

about the mobileconfig check this links

https://developer.apple.com/library/content/documentation/
NetworkingInternet/Conceptual/iPhoneOTAConfiguration/
profile-service/profile-service.html

https://ryanbritton.com/2016/07/creating-a-mobileconfig-
file-to-capture-ios-udid-information/

http://www.joshwright.com/tips/getting-an-iphone-udid-from-mobile-safari

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hunk/get-UDID/issues/1#issuecomment-302956745>, or mute
the thread

**Comment by hunk** [comment]
Yes, it's an XML file, open the file and edit wherever you need, set your correct URL, and if you want to change the PayloadUUID use `uuidgen` command
